### ISSUE TITLE
Trochę nie RESTowe wdrożenie paginacji i wyszukiwania ;)

### ISSUE THREAD

**Issue by NataliaTI** [canicjusz/trol-api#21]
Do paginacji w REST API raczej powinniśmy użyć parametrów w url, niż tworzyć nową ścieżkę typu posts/page/ 

https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#pagination

Podobnie z wyszukiwaniem, w kontekście api możemy to nazwać filtrowaniem zwracanych danych, pod linkiem wyżej jest też przykład odnoszący się do filtrowania

**Comment by NataliaTI** [comment]
@canicjusz @SealSneezy 

- [x] po co after_id? https://prnt.sc/21vwt0e
- [x] czy fakt że wyszukiwanie i stronicowanie możemy używać wyłącznie zamiennie to Wasza intencja czy przypadek?

**Comment by canicjusz** [comment]
> po co after_id?

```after_id``` to id początkowego posta. Podobny przykład był w podanym przez Panią linku w sekcji [seek pagination](https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#seek-pagination). Jedyną różnicą u nas, jest to, że parametr ```after_id``` nie jest opcjonalny (trzeba podać 0, aby otrzymać najświeższe posty).

>  czy fakt że wyszukiwanie i stronicowanie możemy używać wyłącznie zamiennie to Wasza intencja czy przypadek?

Tak właśnie było zaplanowane.
