### ISSUE TITLE
Drobne korekty do struktury bazy ;)

### ISSUE THREAD

**Issue by NataliaTI** [canicjusz/trol-api#3]
Jeszcze kilka detali ;)

### 1. Tabela `Posts`

- [x] w polu `ID` raczej nie spodziewamy się wartości ujemnych, więc dodajmy atrybut `unsigned`
- [x] pole `Author` jak wyżej
- [x] pole `Viewcount` jak wyżej
- [x] jeśli dobrze pamiętam i pole `Content-shortened` odpowiada za krótki tekst, będący zajawką posta na liście wpisów, to raczej nie spodziewamy się tutaj dużych bloków tekstu, więc bardziej optymalnym typem pola byłby varchar z ograniczeniem do kilkuset znaków, na oko na projekcie i tak nie wyświetlamy więcej niż 200 znaków
- [x] pole `Categories` o ile pamiętam ma być tablicą id w formie json, więc tutaj typ pola powinniśmy ustawić spójnie z polem `Authors.Posts` na json lub oba pola na varchar z ograniczeniem do max kilkuset znaków, pole typu json w takim przypadku będzie rezerwowało więcej miejsca na dysku, niż varchar

### 2. Tabela `Categories`

- [x] tutaj chyba zgubiło się ID? Myślę, że warto aby było jednak, dużo łatwiej jest porównywać wartości liczbowe niż ciągi znaków, silnikowi bazy będzie lżej ;)
- [x] pole `Name` raczej również powinno być typu varchar zamiast text, nazwy kategorii zwykle nie są szczególnie długie, więc nie ma potrzeby marnować miejsca ;)

### 3. Tabela `Authors`

- [x] w polu `ID` raczej nie spodziewamy się wartości ujemnych, więc dodajmy atrybut `unsigned`
- [x] pola `Name`, `Avatar`, `Bio` - raczej varchar, to krótkie teskty, ewentualnie `Bio` mogłoby być typu text, gdybyśmy chcieli stworzyć stronę autora, gdzie będzie więcej informacji na jego temat

Klucze obce `Posts_fk1` oraz `Authors_fk0` chyba nam nie zadziałają ;)

**Comment by canicjusz** [comment]
Nie dodawaliśmy `unsigned` do pól `ID`, ponieważ stosując automatyczną inkrementację, nigdy nie będzie liczby ujemnej.

**Comment by canicjusz** [comment]
- [x] `Content-shortened` na `Content_shortened` trza zmienić bo się sypie w SQL

**Comment by canicjusz** [comment]
Jeszcze do dodania `CategoryID` w tabeli `Posts`
